services:
  web:
    build: ./corpwebsite/
    restart: always
    # command: tail -f /dev/null
    command: npx next start
    volumes:
      - ./corpwebsite/:/app/
      - /app/node_modules
    env_file: ./corpwebsite/.env.production
    ports:
      - "3030:3000"
    dns:
      - 192.168.1.1

