import type { Metadata } from "next";
import "./globals.css";
import { Footer } from "../components/layouts/footer/footer"
import '@/styles/globals.scss'; 

import { SourceSansPro, DBHelvethaicaX, Publico } from '@/styles/fonts';
import {useCurrentLocale} from '@/hooks/useI18n';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default  function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale =  useCurrentLocale()
  return (
    <html lang={locale}>
      <body className={`${DBHelvethaicaX.variable} ${SourceSansPro.variable} ${Publico.variable} ${locale === 'th' ? DBHelvethaicaX.className : SourceSansPro.className}`}>
        {children}
      <Footer />
      </body>
    </html>
  );
}
