import type { Metadata } from "next";
import "./globals.css";
import { Footer } from "../components/layouts/footer/footer"
import '@/styles/globals.scss'; 

import { SourceSansPro, DBHelvethaicaX, Publico } from '../styles/fonts';
import {getCurrentLocale} from '../hooks/useI18nServer';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getCurrentLocale()
  return (
    <html lang={locale}>
      <body className={`${DBHelvethaicaX.variable} ${SourceSansPro.variable} ${Publico.variable} ${locale === 'th' ? DBHelvethaicaX.className : SourceSansPro.className}`}>
        {children}
      <Footer />
      </body>
    </html>
  );
}
